### ISSUE TITLE
请问是否支持USB3.0接口的相机使用

### ISSUE THREAD

**Issue by lovechang1986** [DIYer22/hik_camera#2]
大佬您好，非常感谢您提供的优秀开源库。
我有一部MV_CH120-10UC，现在想使用USB3.0接口在jetson orin nano平台使用，不知道您的这个库是否支持？
另外我可有偿请您支持，不知道有时间没有?
我的联系方式QQ:309026438,感谢

**Comment by DIYer22** [comment]
抱歉, 我的业务都基于网线, 所以没有对 USB 支持, 现阶段也没时间继续开发 hik_camera. 但欢迎你修改代码提 pull request 来支持 USB, 贡献给大家用.
